name: Build and propose (Vite) into GitHub Pages docs subfolder (services/web-frontend-vite)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write # PR 브랜치에 커밋 생성
  pull-requests: write # PR 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (cache by ROOT lock)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json # 루트 lock

      - name: Install (root)
        run: npm ci

      - name: Build Vite (workspace)
        run: npm run build -w ./services/web-frontend-vite

      - name: Stage docs subtree
        run: |
          mkdir -p docs/web-frontend-vite
          # 기존 산출물만 정리 (다른 docs 콘텐츠는 건드리지 않음)
          rm -rf docs/web-frontend-vite/*
          cp -r services/web-frontend-vite/dist/* docs/web-frontend-vite/
          # SPA fallback (BrowserRouter일 때)
          cp docs/web-frontend-vite/index.html docs/web-frontend-vite/404.html || true

      # docs 하위 변경만 포함하는 PR 자동 생성
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: publish Vite build to docs/web-frontend-vite'
          title: 'Publish Vite build to docs/web-frontend-vite'
          body: '자동 생성된 배포 PR입니다. 머지하면 GitHub Pages가 업데이트됩니다.'
          branch: ci/docs-web-frontend-vite
          base: main
          add-paths: |
            docs/web-frontend-vite/**
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          signoff: false
          labels: |
            ci
            pages
