name: Deploy web-frontend-vite to gh-pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-frontend-vite/**'
      - '.github/workflows/deploy-gh-pages-web-frontend-vite.yml'
  workflow_dispatch:

# gh-pages 브랜치로만 정적 파일 푸시 → main은 수정하지 않음
permissions:
  contents: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # gh-pages를 덮어쓸 일이 없도록 fetch-depth 충분히
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web-frontend-vite/package-lock.json

      - name: Install
        working-directory: web-frontend-vite
        run: npm ci

      - name: Build
        working-directory: web-frontend-vite
        run: npm run build

      # ===== (옵션) BrowserRouter 쓸 때만 켜세요 =====
      # - name: Add 404 redirect for SPA (optional)
      #   working-directory: web-frontend-vite/dist
      #   run: |
      #     cat > 404.html << 'EOF'
      #     <!doctype html><html><head><meta charset="utf-8">
      #     <meta http-equiv="refresh" content="0;url=/dev_portfolio/web-frontend-vite/">
      #     <script>
      #       (function(){
      #         var base='/dev_portfolio/web-frontend-vite/';
      #         var after = location.pathname.split(base)[1] || '';
      #         location.replace(base + (after||'') + location.search + location.hash);
      #       })();
      #     </script></head><body></body></html>
      #     EOF
      # ============================================

      - name: Deploy to gh-pages (keep branch clean)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # dist를 gh-pages 루트의 하위 폴더로 배치 → /web-frontend-vite/ 경로 확보
          publish_dir: web-frontend-vite/dist
          destination_dir: web-frontend-vite
          # 여러 서브앱을 gh-pages에 공존시키려면 force_orphan: false 유지
          force_orphan: false
          # 커스텀 도메인 쓰지 않으면 생략
          # cname: your.domain
