name: Build & Deploy - docs/web-frontend-vite (Vite React)

on:
  push:
    branches: [ "main" ]
    # 배포 커밋으로 인한 무한 루프 방지
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web-frontend-vite/package-lock.json

      - name: Install
        working-directory: web-frontend-vite
        run: npm ci

      - name: Build
        working-directory: web-frontend-vite
        run: npm run build

      - name: Prepare target folder
        run: |
          mkdir -p docs/web-frontend-vite
          rm -rf docs/web-frontend-vite/*

      - name: Copy build to docs/web-frontend-vite
        run: cp -r web-frontend-vite/dist/* docs/web-frontend-vite/

      - name: Add .nojekyll (prevent underscore issues)
        run: touch docs/.nojekyll

      # ===== (옵션) BrowserRouter 사용할 때만 활성화 =====
      # - name: Add 404 redirect for SPA (optional)
      #   run: |
      #     cat > docs/web-frontend-vite/404.html << 'EOF'
      #     <!doctype html><html><head><meta charset="utf-8">
      #     <meta http-equiv="refresh" content="0;url=/dev_portfolio/web-frontend-vite/">
      #     <script>
      #       (function(){
      #         var repo = 'dev_portfolio';
      #         var base = '/' + repo + '/web-frontend-vite/';
      #         var after = location.pathname.split(base)[1] || '';
      #         var target = base + (after || '');
      #         location.replace(target + location.search + location.hash);
      #       })();
      #     </script>
      #     </head><body></body></html>
      #     EOF
      # ===============================================

      - name: Commit & Push to main (docs only)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: deploy web-frontend-vite to docs/web-frontend-vite"
          file_pattern: docs/**
