# pages.yml
name: Deploy Portfolio to Pages
on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/portfolio/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Portfolio
        run: echo "Building portfolio site..."
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4